### ISSUE TITLE
tkinter fixes

### ISSUE THREAD

**Issue by ian1dunn** [Neurotechnology-Exploration-Team/DataCollector#2]

**Comment by Matt-London** [comment]
Just did some work to refactor the `main.py` tkinter stuff into a class with static methods. I also added a deny button to the acceptance window, vertical scrolling with the wheel, and organized the graphs side-by-side as well as vertically so it takes up less space. I'm having a lot of bugs so I will fix those tomorrow and hopefully get everything merged.
