### ISSUE TITLE
FUCKING TESTS IRB SHIT

### ISSUE THREAD

**Issue by Alexandr5656** [Neurotechnology-Exploration-Team/DataCollector#43]
Ok I was thinking about the tests and how maybe the imagining movement was a bit too quick so i dove into the old code and the submission and found these documents. First from the procedure for the subjects 
> RANDOMIZE THESE FIRST!
a.1 - eyes open
a.2 - eyes closed 
b - blink
c.1 - brow furrow 
c.2 - brow unfurrow
d - stationary floating
e - float left
f - float right
g - float up
h - float down
i - select

> RANDOMIZE THESE AFTER THE ABOVE ARE COMPLETED!
j - stationary float to select
k - stationary float to float left
l - stationary float to float right
m - stationary float to float up
n - stationary float to float down
o - eye open and close
p - brow furrow and unfurrow

> In j-n the desired state will be shown on the screen and a constant frequency sinusoid will be played over a short duration to signify state change.
In d-i the desired state will NOT be shown on the screen and no sound will be played. 
In a-c plays the sound but shows no image.
This difference is to allow for separation of the effects of these switching stimuli from the actual desired action.

> For all switching cases, indicators (auditory and visual) will be automatically displayed at a variable rate, ranging from two and a half seconds up to six seconds, up until 30 trials have been performed. You will start by asking the participant to open their eyes and relax and starting the recording unless the instructions below specify otherwise. Five seconds after the recording is complete, indicators will stop. Five seconds before starting to present stimuli will be allotted to allow the subject to relax.

> Wait for at least 10 seconds after the program finishes (a popup will appear) before stopping the recording and notifying the subject verbally that the test is completed. The number of elapsed recording seconds is visible in the bottom left corner of the LSL Lab Recorder program. 
And heres from the researcher
> RANDOMIZE THESE!
SetEyeOpenTrial
SetEyeClosedTrial
SetBlinkTrial
SetBrowFurrowedTrial
SetBrowUnforrowedTrial
SetStopTrial
SetLeftTrial
SetRightTrial
SetUpTrial
SetDownTrial
SetSelectTrial
SetStopToSelectTrial
SetStopToLeftTrial
SetStopToRightTrial
SetStopToUpTrial
SetStopToDownTrial
SetEyeOpenCloseTrial
SetBrowFurrowUnforrowTrial

> For all switching cases, indicators (auditory and visual) will be automatically displayed at a variable rate, ranging from two and a half seconds up to six seconds, up until 30 trials have been performed. For non-switching cases, indicators will be displayed in 20 second intervals. You will start by asking the participant to open their eyes and relax and starting the recording unless the instructions below specify otherwise. Five seconds after the recording is complete, indicators will stop. Five seconds before starting to present stimuli will be allotted to allow the subject to relax.

> Wait for at least 10 seconds after the program finishes (a popup will appear) before stopping the recording and notifying the subject verbally that the test is completed. The number of elapsed recording seconds is visible in the bottom left corner of the LSL Lab Recorder program. 

What i think we need to do is make blinking audio only and have a label everytime the audio is played and have a file that has the events seperatly. For other states that are constant such as A and C-I we need to have it so that the time inbetween the buffers is labeled as what the test is looking for as well as getting rid of any images and audios for those. That is because the subject should be imagining themselves moving constantly. the transition states also need to get the second between pictures removed as well as i believe doubling the time that the action image is displayed.

**Comment by ian1dunn** [comment]
All three types of tests (blink, constant, transition) should be complete. Abort button has also been added from #41. I just need to do a little more testing before I make a PR.
